version: '3.7'
services:
  rabbitmq3:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: 'izzulsecret'
    volumes:
      - ./db-data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672